Repository Ezehkiel/STI_PRO1, pull requests merged in 2019-10, with the labels that each got.

#11 Feature/login page
  site/databases/database.sqlite
  site/databases/sti_project1
  site/html/admin.php
  site/html/databaseLib/connectionDatabase.php
  site/html/databaseLib/requestsDatabase.php
  site/html/example.php
  site/html/helloworld.php
  site/html/home.php
  site/html/inbox.php
  site/html/includes/foot.php
  site/html/includes/head.php
  site/html/includes/menu.php
  site/html/login.php
  site/html/logout.php
  site/html/newMessage.php
  site/html/phpliteadmin.php
  site/html/style/css/bootstrap-grid.css
  site/html/style/css/bootstrap-grid.css.map
  site/html/style/css/bootstrap-grid.min.css
  site/html/style/css/bootstrap-grid.min.css.map
  site/html/style/css/bootstrap-reboot.css
  site/html/style/css/bootstrap-reboot.css.map
  site/html/style/css/bootstrap-reboot.min.css
  site/html/style/css/bootstrap-reboot.min.css.map
  site/html/style/css/bootstrap.css
  site/html/style/css/bootstrap.css.map
  site/html/style/css/bootstrap.min.css
  site/html/style/css/bootstrap.min.css.map
  site/html/style/css/style.css
  site/html/style/js/bootstrap.bundle.js
  site/html/style/js/bootstrap.bundle.js.map
  site/html/style/js/bootstrap.bundle.min.js
  site/html/style/js/bootstrap.bundle.min.js.map
  site/html/style/js/bootstrap.js
  site/html/style/js/bootstrap.js.map
  site/html/style/js/bootstrap.min.js
  site/html/style/js/bootstrap.min.js.map
  site/html/utility/utility.php
Labels: Need review

#14 Add defaults values in database
  site/databases/sti_project1
Labels: Need review

#13 Added the feature to send a message to someone
  site/html/databaseLib/requestsDatabase.php
  site/html/newMessage.php
Labels: Done

#15 Admin menu
  site/html/addUser.php
  site/html/admin.php
  site/html/databaseLib/requestsDatabase.php
  site/html/deleteUser.php
  site/html/modifyUser.php
Labels: Need review

#20 Admin pages protection
  site/html/addUser.php
  site/html/admin.php
  site/html/databaseLib/requestsDatabase.php
  site/html/deleteUser.php
  site/html/modifyUser.php
  site/html/utility/utility.php
Labels: Done

#18 Change password for users
  site/html/changePassword.php
  site/html/databaseLib/requestsDatabase.php
  site/html/includes/menu.php
Labels: Done

#21 Validity check before login
  site/html/databaseLib/requestsDatabase.php
  site/html/login.php
Labels: Need review

#23 Login check
  site/html/addUser.php
  site/html/databaseLib/requestsDatabase.php
  site/html/deleteUser.php
Labels: Need review

#30 Remove the field Old password
  site/html/modifyUser.php
Labels: Need review

#29 Add back button in every page
  site/html/addUser.php
  site/html/admin.php
  site/html/changePassword.php
  site/html/inbox.php
  site/html/includes/head.php
  site/html/modifyUser.php
  site/html/newMessage.php
Labels: Need review

#32 Fix errors messages for be more clear
  site/html/addUser.php
  site/html/changePassword.php
  site/html/deleteUser.php
  site/html/modifyUser.php
Labels: In review

#31 Fix/message time
  site/html/databaseLib/requestsDatabase.php
  site/html/inbox.php
  site/html/showMessage.php
Labels: Need review

#33 Setup the date in the PHP instead of default database value.
  deploy.sh
  site/databases/sti_project.sqlite
  site/databases/sti_project1.sqlite
  site/html/databaseLib/requestsDatabase.php
  site/html/includes/head.php
  site/html/modifyUser.php
  site/html/newMessage.php
Labels: Done

#34 Add presentation
  presentation_projet1_sti_hunkeler_poulard.pdf
Labels: Need review

#36 Fix/error message login
  site/html/login.php
Labels: Done
